version: '3'

services:

  mariadb:
    networks:
      - inception_network
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb-database:/var/lib/mysql
    restart: on-failure

  wordpress:
    networks:
      - inception_network
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html/
    depends_on:
      - mariadb

  nginx:
    networks:
      - inception_network
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    depends_on: 
      - wordpress
    volumes:
      - wordpress-files:/var/www/html/

volumes:
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tbousque/data/wordpress"

  mariadb-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tbousque/data/mariadb"


networks:
  inception_network:
    driver: bridge