version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress-database:/var/lib/mysql/wordpress

volumes:
  wordpress-database: