services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always